### ISSUE TITLE
Kokkos example expects to be able to write in install prefix at cmake time

### ISSUE THREAD

**Issue by stelleg** [lanl/kitsune#25]
Lines 70-72 of clang/kitsune/examples/kokkos/CMakeLists.txt seem problematic: 

```
CMake Error: Could not open file for write in copy operation /usr/local/kitsune/examples/kokkos/run-kokkos-examples.sh.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /home/george/llvm-project/clang/kitsune/examples/kokkos/CMakeLists.txt:70 (configure_file):
  configure_file Problem configuring file
```

**Comment by pmccormick** [comment]
Thanks.  Looks like I missed a file many moons ago...   I'll take a closer look but should be an easy fix.

**Comment by pmccormick** [comment]
Ah...  Nope, that's not the problem -- my guess is you have CMAKE_INSTALL_PREFIX set to something that you don't have write permissions for.  But this plan isn't cool -- should probably be the project binary dir vs. the install dir...

**Comment by stelleg** [comment]
Right, the install prefix generally isn't writable by default on most systems at cmake time, only at install time.

**Comment by pmccormick** [comment]
Pushed a fix.  Hopefully not too quickly...   ;-)

**Comment by stelleg** [comment]
Yep, that seems to have done the trick.
